### ISSUE TITLE
update data before PPG shutters (May 3, 2026)

### ISSUE THREAD

**Issue by PatMyron** [PatMyron/wpial#5]
remember #7 

```yaml
on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Enables on-demand/manual triggering
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: touch hi.txt
      - uses: peter-evans/create-pull-request@v6
```
